version: "3.8"
services:
  backend:
    build:
      context: ./backend
    image: backend
    container_name: backend
    environment:
      - BASE_URL=http://localhost:3001
    ports:
      - "9000:8000"

  frontend:
    build:
      context: ./frontend
    image: frontend
    container_name: frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:9000
    ports:
      - "3001:3000"
    depends_on:
      - backend